### ISSUE TITLE
Nil vs Nothing

### ISSUE THREAD

**Issue by mlhetland** [TotalVerb/SExpressions.jl#4]
In 0.7 onward, might it make sense to have
```
const Nil = Nothing
const nil = nothing
```
rather than defining your own type?

**Comment by TotalVerb** [comment]
The issue is that a `Nil` is-a `List`, which conforms to the Julia iterator interface (i.e. supports `length`, `start`, etc.). At the same time, it would be nice if `Nil` is-a `Nothing`. The problem is that `Nothing` does not conform to the Julia iterator interface, and adding those functions would be type punning.

I agree that it would be nice if the list representation introduced as few new types as possible, but it is also convenient to be able to access it as if it were a Julia list.

**Comment by mlhetland** [comment]
Ah, right! That totally makes sense.
