### ISSUE TITLE
please consider registration in the General registry

### ISSUE THREAD

**Issue by tpapp** [TotalVerb/SExpressions.jl#6]
Now that @RobBlackwell is also using it in RobBlackwell/Swank.jl, it would make installation easier.

**Comment by TotalVerb** [comment]
Yes, this can be arranged. Since I do not have support for a lot of reader macros usually found in real s-expression syntaxes, I have traditionally deferred registering it so as not to present this package as complete. But I am happy to register it if it is already being used in the wild; will do so later today. (Many of the reader macros can be added without breaking existing parsing, so I am not too concerned about needing to make breaking changes soon after registration.)

**Comment by TotalVerb** [comment]
I have set up the PR to General to register the package, and now we need only wait for the 3 day grace period. I will close this issue after it has been merged. https://github.com/JuliaRegistries/General/pull/7729

**Comment by TotalVerb** [comment]
This is done now.
